### ISSUE TITLE
false positive when scanning Dist::Zilla::Plugin::Rinci::Wrap 0.07

### ISSUE THREAD

**Issue by perlancar** [moznion/Perl-PrereqScanner-Lite#10]
Note: extra scanners like Moose and Version are activated.

    % scan-prereqs-using-perl-prereqscanner lib/Dist/Zilla/Plugin/Rinci/Wrap.pm 
    Dist::Zilla::Role::FileFinderUser=0
    Dist::Zilla::Role::FileMunger=0
    Module::CoreList=0
    Moose=0
    Perinci::Sub::Wrapper=0
    experimental=0
    namespace::autoclean=0
    perl=5.010001
    strict=0
    warnings=0
    
    % scan-prereqs-using-perl-prereqscanner-lite lib/Dist/Zilla/Plugin/Rinci/Wrap.pm 
    :InstallModules=0
    Dist::Zilla::Role::FileFinderUser=0
    Dist::Zilla::Role::FileMunger=0
    Module::CoreList=0
    Moose=0
    Perinci::Sub::Wrapper=0
    experimental=0
    namespace::autoclean=0
    perl=5.010001
    strict=0
    warnings=0

As you can see, P:PS:Lite incorrectly detects `:InstallModules`, which comes from this line:

    with (
        'Dist::Zilla::Role::FileMunger',
        'Dist::Zilla::Role::FileFinderUser' => {
            default_finders => [':InstallModules'],
        },
    );

**Comment by moznion** [comment]
I'm sorry for the delay in dealing. I've just fixed this problem.
