### ISSUE TITLE
t/30_v_string.t fails with latest version.pm development version

### ISSUE THREAD

**Issue by eserte** [moznion/Perl-PrereqScanner-Lite#15]
See http://analysis.cpantesters.org/solved?distv=Perl-PrereqScanner-Lite-0.26#mod%3Aversion for statistical analysis — the t/30_v_string.t test fails with version.pm 0.9912_02.

**Comment by andk** [comment]
It's worse than that: it fails with version.pm 0.9912_02 and all later versions. Matrix is getting more and more red:

http://matrix.cpantesters.org/?dist=Perl%3A%3APrereqScanner%3A%3ALite

**Comment by zakame** [comment]
Seems like the test itself is broken, as my understanding of CPAN::Meta::Requirements is that it would return the normalized version numbers as opposed to the form written down by the author.

**Comment by jkeenan** [comment]
With perl-5.25.8:
```
t/20_left_paran_is_behind_at_module_name.t .. ok

    #   Failed test at t/30_v_string.t line 16.
    # Compared $data->{"File\:\:Temp"}
    #    got : 'v0.12.0'
    # expect : 'v0.1_2'
    # Looks like you failed 1 test of 1.

#   Failed test 'basic'
#   at t/30_v_string.t line 19.
# Looks like you failed 1 test of 1.
t/30_v_string.t ............................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
t/40_extra_scanners.t ....................... ok

Test Summary Report
-------------------
t/30_v_string.t                           (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=11, Tests=16,  1 wallclock secs ( 0.03 usr  0.01 sys +  0.51 cusr  0.05 csys =  0.60 CPU)
Result: FAIL
```

**Comment by Grinnz** [comment]
17:57:42 <Grinnz> to keep that test, what i would do is change it from a string comparison to a version->parse comparison
17:58:57 <Grinnz> or maybe just stick version->parse('v0.1_2')->normal as the string to compare

**Comment by moznion** [comment]
#16 fixes this issue. Thank you reporting.
