### ISSUE TITLE
Miss detect some modules at Perinci::CmdLine::Base 0.72

### ISSUE THREAD

**Issue by perlancar** [moznion/Perl-PrereqScanner-Lite#5]
File is at: https://github.com/perlancar/perl-Perinci-CmdLine-Lite/tree/ee69a27b8878b019fbe221f3c3eec142f5c5e002/lib/Perinci/CmdLine

    % setop --diff <( scan-prereqs-using-perl-prereqscanner lib/Perinci/CmdLine/Base.pm ) <( scan-prereqs-using-perl-prereqscanner-lite lib/Perinci/CmdLine/Base.pm )
    File::Which=0
    experimental=0
    if=0

**Comment by moznion** [comment]
Please detail about `scan-prereqs-using-perl-prereqscanner` and `scan-prereqs-using-perl-prereqscanner-lite`.

**Comment by moznion** [comment]
I think, `experimental` and `if` have been detected, it is a bug.
However it detects `File::Which`, it is not bug of this module. This module shouldn't have responsibility for core-module handling.

**Comment by perlancar** [comment]
> Please detail about scan-prereqs-using-perl-prereqscanner and scan-prereqs-using-perl-prereqscanner-lite.

https://github.com/perlancar/scripts/blob/master/scan-prereqs-using-perl-prereqscanner
https://github.com/perlancar/scripts/blob/master/scan-prereqs-using-perl-prereqscanner-lite

As for the setop command it's installable via CPAN (App::setop). The previous command-line basically just compares output by Perl::PrereqScanner which are not output by Perl::PrereqScanner::Lite.

**Comment by perlancar** [comment]
> However it detects File::Which, it is not bug of this module. This module shouldn't have responsibility for core-module handling.

Sorry, I don't understand what you said. It shouldn't matter if a require/use statement is for core/non-core module right? And the output of Perl::PrereqScanner::Lite should be the same as Perl::PrereqScanner, shouldn't it? And anyway, the source code being scanner (lib/Perinci/CmdLine/Base.pm) does contain these statements:

    use experimental 'smartmatch';

        require File::Which;

    use if  $INC{'Perinci/CmdLine.pm'}, qw(Moo);
    use if !$INC{'Perinci/CmdLine.pm'}, qw(Mo  build default);

Shouldn't they be detected, regardless of whether the required module is a core module (or even exists) or not.

**Comment by moznion** [comment]
Ah, I'm sorry, I took a misunderstanding.

These are P::P::Scanner::Lite's bug and Compiler::Lexer's bug.
I will try to fix them.

**Comment by moznion** [comment]
I proposed a pull request to Compiler::Lexer to fix this issue.
https://github.com/goccy/p5-Compiler-Lexer/pull/57

**Comment by perlancar** [comment]
Thanks moznion, File::Which, experimental, and if are now detected. There are some more modules missed though on another of my module. I've opened another issue.
