### ISSUE TITLE
Issues with v-strings

### ISSUE THREAD

**Issue by miyagawa** [moznion/Perl-PrereqScanner-Lite#6]
```perl
use Perl::PrereqScanner::Lite;
warn Perl::PrereqScanner::Lite->new->scan_string("use Plack v1.1_1;")->requirements_for_module("Plack")'
```

This emits `v1.1.0`, where it's expected to have `v1.1.1` (or `v1.1_1`).

I guess it has to `eval` the given string when it is a v-string.

redirected from https://github.com/miyagawa/Dist-Milla/issues/32

**Comment by moznion** [comment]
Thank you for your reporting.

This is a matter of Compiler::Lexer's interpretation thus it should be fixed itself. I'll try it.
Apart from that I'll apply a workaround into Perl::PrereqScanner::Lite to resolve this problem.

**Comment by moznion** [comment]
@miyagawa 

https://github.com/moznion/Perl-PrereqScanner-Lite/blob/fix/6_v-string_problem/t/resources/v_string.pl

This target emits `File::Temp => 'v0.1_2'`.
Is it correct?

**Comment by miyagawa** [comment]
LGTM!

**Comment by moznion** [comment]
Thanks a lot!
