### ISSUE TITLE
Miss detect some modules for Perinci::CmdLine::Classic 1.45

### ISSUE THREAD

**Issue by perlancar** [moznion/Perl-PrereqScanner-Lite#8]
For the scripts used, please see #5.

    % setop --diff <(scan-prereqs-using-perl-prereqscanner lib/Perinci/CmdLine/Classic.pm) <(scan-prereqs-using-perl-prereqscanner-lite lib/Perinci/CmdLine/Classic.pm)
    Color::Theme::Role::ANSI=0
    Perinci::CmdLine::Base=0
    Perinci::CmdLine::Classic::Role::Help=0
    Term::App::Role::Attrs=0

The relevant statements in lib/Perinci/CmdLine/Classic.pm:

    with 'Color::Theme::Role::ANSI' unless $ENV{COMP_LINE};

    extends 'Perinci::CmdLine::Base';

    with 'Perinci::CmdLine::Classic::Role::Help' unless $ENV{COMP_LINE};

    with 'Term::App::Role::Attrs' unless $ENV{COMP_LINE};

Those are all Mo/Moo/Moose-related..

**Comment by moznion** [comment]
You can use [Perl::PrereqScanner::Lite::Scanner::Moose](https://metacpan.org/pod/Perl::PrereqScanner::Lite::Scanner::Moose) via `add_extra_scanner()` method.

**Comment by perlancar** [comment]
I see, thanks. Although I wonder why the extra scanner(s) are not added by default, if the goal is to be a drop-in replacement for Perl::PrereqScanner (assuming that is the case).

**Comment by moznion** [comment]
Mechanism to include other modules of Moose family and UNIVERSAL (`VERSION()` method), they are not supported by vanilla  perl interpreter. So I stripped them from the core of scanner.
(Another reason, they make scanner a bit slow... Yes, it is unfair reason!)

Do you think these extra scanners should be included in the core?
I've been thought that I can put decision to include or not into user's hands.

**Comment by perlancar** [comment]
Well, as a user, looking at the name I do expect Perl::PrereqScanner and Perl::PrereqScanner::Lite to act the same and be a drop-in replacement for each other.

Anyway, how about adding the extra scanner dynamically/on-demand (i.e. add it after 'use Moose' or 'use Moo' is encountered in the source code). Is it feasible technically?

**Comment by moznion** [comment]
> Well, as a user, looking at the name I do expect Perl::PrereqScanner and Perl::PrereqScanner::Lite to act the same and be a drop-in replacement for each other.

I agree with you.

> Anyway, how about adding the extra scanner dynamically/on-demand (i.e. add it after 'use Moose' or 'use Moo' is encountered in the source code). Is it feasible technically?

Nice idea. I think it is possible but I should consider about performance.
I'll try to implement such system.
